service: infrastructure
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-lift
  - serverless-bundle
